### ISSUE TITLE
video in the "Work With Us" page

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#10]
<img width="1430" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/cd3cdfe2-5706-4c80-a0d2-e7aaf2deb33c">

After the Our Culture panel and before the Job Openings, I would like a section where I can embed a video from Youtube

**Comment by davewibisono** [comment]
Noted. I will add a YouTube embed video . Could you provide the Video URL?

**Comment by bendichter** [comment]
I don't have it yet. You can just put in a random video for now, e.g. this one https://www.youtube.com/watch?v=fRhuwBLs7tM

**Comment by davewibisono** [comment]
Added. Done
