### ISSUE TITLE
Add links on software cards

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#11]
<img width="1340" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/b38ad535-ec8c-42b4-afad-c0ae8a72190f">

Each of these cards should have two links, one for Documentation and one for GitHub Repo

**Comment by davewibisono** [comment]
So just add two buttons ?
[Documentation]  [Github Repo]

**Comment by bendichter** [comment]
yes
