### ISSUE TITLE
Software cards to contain rich text

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#17]
<img width="935" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/c76e24b8-d035-4151-a1f3-348ecef5b4de">

Would it be possible to allow for rich text within the content section of the software tools? I would like to be able to enter things like bulleted lists, which is currently difficult with this paragraph style.

**Comment by davewibisono** [comment]
Added. Done
