### ISSUE TITLE
Unable to adjust slug of blog post

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#18]
<img width="1255" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/ca7268ad-4f18-4b4d-8d86-b1ae9e88e6ef">

I have edit this blog post but it looks like I am unable to edit the URL.

**Comment by davewibisono** [comment]
Done. Edit or change the URL to be in the code tab>Content > Blog > old_post_name.md 
Change old_post_name.md to new_post_name.md 
https://voluble-souffle-995141.netlify.app/blog/catalystneuro-company-retreat-in-barcelona/
