### ISSUE TITLE
Option to add photo gallery to blog posts

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#19]
I currently am writing a blog post about a company retreat, and I would like to be able to include a photo gallery. Not all blog posts would need this. I would be fine with adding HTML to the markdown in order to include this

**Comment by bendichter** [comment]
https://github.com/haltakov/simple-photo-gallery?tab=readme-ov-file

this would work

**Comment by bendichter** [comment]
https://hugocodex.org/add-ons/image-gallery/

This would also work

**Comment by davewibisono** [comment]
This one is done. You can use the code snippet in the blog. You have to create a folder and place a set of images for the gallery. In this example, I have created a 'team' folder under '/assets/img/'.

<img src="/assets/img/0v8a2080.jpg" width=400 height=200>
{{< snap-gallery src="/assets/img/team/" mode="slideshow" >}}
