### ISSUE TITLE
Images added to blog posts are missing on live site

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#20]
<img width="1009" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/e5f781cf-a96f-4cdc-8422-22d39ef932e4">

<img width="1482" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/c80a1bb4-5d17-41d8-9443-9dfe2df3122f">

**Comment by davewibisono** [comment]
Fixed. Done
