### ISSUE TITLE
netlify images config

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#28]
There is some issue with netlify now.

1. When I try to select a new image it does not see any of the assets that have already been uploaded.
2. When I upload an asset it does not appear on the page.

<img width="971" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/c55d86c8-4266-4a1d-bd2f-1e88aaf0b4c6">

**Comment by davewibisono** [comment]
Please hold on. I'm working on the image gallery.

**Comment by davewibisono** [comment]
Done
