### ISSUE TITLE
teams page bugs

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#3]
I tested the teams page and it works. A few bugs:

* [x] The social fields, e.g. "FACEBOOK" should not be required. Currently, they are all "/" by default, which links to the main page. If I remove the slash, I am unable to save the form because they are required fields.
* [ ] "MORE BIO" should be optional
* [x]  "COLLABORATORS" and "ALUMNI" fields do not accept spaces.

**Comment by davewibisono** [comment]
1. Social field - If you leave the field empty, that icon will not show on the page.
2. Read More - I added it to maintain a standard height for all profiles. Let me know your thoughts.
3. 'COLLABORATORS' and 'ALUMNI'
Fixed. You can add spaces.

**Comment by bendichter** [comment]
Could you enforce a standard height for the profile cards as a property of the profile card?

**Comment by davewibisono** [comment]
Done
