### ISSUE TITLE
Allow CMS to submit PRs?

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#4]
Is there a way to have the option of having the CMS submit a pull request instead of pushing changes directly to the main branch?

**Comment by davewibisono** [comment]
There is no such option

**Comment by davewibisono** [comment]
There is no such option

**Comment by bendichter** [comment]
@davewibisono what about this? https://docs.netlify.com/site-deploys/deploy-previews/

**Comment by bendichter** [comment]
@davewibisono could you please reopen this?
