### ISSUE TITLE
alignment of profile cards on home page

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#6]
<img width="1409" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/792f1156-ae24-4bb7-8bef-b7af00590b2c">

Is there any way to make these cards uniformly aligned?

**Comment by davewibisono** [comment]
This is due to the image width and height, as well as the length of the text. Let me set a fixed size for all client images and limit the text height to three lines. Ideally, the text shouldn't exceed three lines. Am I right?

**Comment by bendichter** [comment]
Right, 3 lines is a good limit

**Comment by davewibisono** [comment]
Done

**Comment by bendichter** [comment]
Could you change this so I get 2 lines for each title? I don't think I can fit enough information in a single line
