### ISSUE TITLE
Create a heading before the job postings

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#9]
<img width="1725" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/a7a052ff-6109-4ba5-8c22-fcb950b3e81a">

Before the job postings could you add a heading that says "Open Positions". If there are no positions open, could you please have text that says "We are not currently hiring"

**Comment by davewibisono** [comment]
I will add the headings

**Comment by davewibisono** [comment]
Added.
